// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQZXVMk7X54l1nAo3C2x-ZQN0KE-bjsw',
    appId: '1:70246344910:web:39bcb48a4595b04d84089f',
    messagingSenderId: '70246344910',
    projectId: 'commrade-manifesto',
    authDomain: 'commrade-manifesto.firebaseapp.com',
    storageBucket: 'commrade-manifesto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiSKk1hqGixc5_ZnK3FNBrKKczRggWrFU',
    appId: '1:70246344910:android:fecaaad5fbeac7a584089f',
    messagingSenderId: '70246344910',
    projectId: 'commrade-manifesto',
    storageBucket: 'commrade-manifesto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDR_wy8ZkB4mzO0D-ZLQ5sNPFWHlryvo',
    appId: '1:70246344910:ios:b77e673bb744053f84089f',
    messagingSenderId: '70246344910',
    projectId: 'commrade-manifesto',
    storageBucket: 'commrade-manifesto.appspot.com',
    iosClientId: '70246344910-i1huq4mbtv7k9e7ncdnqqlgdj5j1jt05.apps.googleusercontent.com',
    iosBundleId: 'com.comrade-manifesto.app',
  );
}
